### ISSUE TITLE
features/plugins

### ISSUE THREAD

**Issue by milimetric** [Quantiply/grafana-druid-wikipedia#1]
Hey this repo seems really cool.  Do you have the grafana plugin for druid that's mentioned in the readme?  I couldn't see the features/ folder that you reference in your symlink instruction and config.js module definition.  Either way, this work and similar visualization work for Druid is really exciting, thanks!

**Comment by theduderog** [comment]
Hi @milimetric,

Yes, the Druid plugin for Grafana is [here](https://github.com/Quantiply/grafana-plugins/tree/master/features/druid).  The way I install it is to download Grafana 1.9.1 as is, open it up and put a sym link to this plugin in the plugins/features directory.

`cd grafana-1.9.1`
`ln -s /path/to/druid/plugin/grafana-plugins/features plugins/features`

**Comment by milimetric** [comment]
Thanks!  You rock, I'll be trying this soon.

**Comment by theduderog** [comment]
Cool.  Let me know how it goes.
